"""Authoritative source catalog for the youth labour-law data pipeline.

The catalogs are declarative only: no request is issued at import time.  Task 1
and Task 2 consume these entries without substituting a different source.
"""

from __future__ import annotations

from typing import Any, Final


LEGAL_SOURCES: Final[tuple[dict[str, Any], ...]] = (
    {
        "document_id": "labor_code_consolidated_18_2026",
        "title": "Văn bản hợp nhất Bộ luật Lao động",
        "document_number": "18/VBHN-VPQH",
        "document_type": "consolidated_text",
        "issuing_authority": "Văn phòng Quốc hội",
        "issued_date": "2026-02-12",
        "source_page_url": "https://congbao.chinhphu.vn/van-ban/van-ban-hop-nhat-so-18-vbhn-vpqh-468971/62878.htm",
        "download_url": None,
        "resolve_download_from_page": True,
        "preferred_format": "docx",
        "fallback_format": "pdf",
        "authoritative": True,
        "normative": False,
        "legal_status": "official_consolidated",
        "active_corpus": True,
        "legal_topics": [
            "probation",
            "probation_salary",
            "employment_contract",
            "apprenticeship",
            "salary",
            "overtime",
            "night_work",
            "annual_leave",
            "personal_leave",
            "unilateral_termination",
            "contract_termination",
            "dismissal",
            "labor_discipline",
            "salary_deduction",
            "salary_delay",
        ],
        "audience_roles": [
            "job_applicant",
            "intern",
            "apprentice",
            "trainee",
            "probationer",
            "employee",
            "former_employee",
            "employer",
        ],
    },
    {
        "document_id": "labor_code_45_2019",
        "title": "Bộ luật Lao động",
        "document_number": "45/2019/QH14",
        "document_type": "law_source_instrument",
        "issuing_authority": "Quốc hội",
        "issued_date": "2019-11-20",
        "effective_date": "2021-01-01",
        "source_page_url": "https://vanban.chinhphu.vn/?classid=1&docid=198540&pageid=27160&typegroupid=3",
        "download_url": "https://datafiles.chinhphu.vn/cpp/files/vbpq/2019/12/45.signed.pdf",
        "local_filename": "labor-code-45-2019-qh14.pdf",
        "authoritative": True,
        "normative": True,
        "legal_status": "source_instrument",
        "active_corpus": False,
    },
    {
        "document_id": "decree_145_2020",
        "title": "Nghị định hướng dẫn Bộ luật Lao động về điều kiện lao động và quan hệ lao động",
        "document_number": "145/2020/NĐ-CP",
        "document_type": "decree",
        "issuing_authority": "Chính phủ",
        "issued_date": "2020-12-14",
        "effective_date": "2021-02-01",
        "source_page_url": "https://vanban.chinhphu.vn/?docid=201967&pageid=27160",
        "download_url": "https://datafiles.chinhphu.vn/cpp/files/vbpq/2020/12/145.signed.pdf",
        "local_filename": "decree-145-2020-labor-relations.pdf",
        "authoritative": True,
        "normative": True,
        "legal_status": "needs_revalidation",
        "active_corpus": True,
        "legal_topics": [
            "employment_contract",
            "salary",
            "overtime",
            "night_work",
            "annual_leave",
            "contract_termination",
            "labor_discipline",
            "dismissal",
        ],
    },
    {
        "document_id": "decree_12_2022",
        "title": "Nghị định xử phạt vi phạm hành chính trong lĩnh vực lao động",
        "document_number": "12/2022/NĐ-CP",
        "document_type": "decree",
        "issuing_authority": "Chính phủ",
        "issued_date": "2022-01-17",
        "effective_date": "2022-01-17",
        "source_page_url": "https://vanban.chinhphu.vn/?classid=1&docid=205182&orggroupid=2&pageid=27160",
        "download_url": "https://datafiles.chinhphu.vn/cpp/files/vbpq/2022/01/12-2022-nd.signed.pdf",
        "local_filename": "decree-12-2022-labor-penalties.pdf",
        "authoritative": True,
        "normative": True,
        "legal_status": "needs_revalidation",
        "active_corpus": True,
    },
    {
        "document_id": "decree_293_2025",
        "title": "Nghị định quy định mức lương tối thiểu đối với người lao động làm việc theo hợp đồng lao động",
        "document_number": "293/2025/NĐ-CP",
        "document_type": "decree",
        "issuing_authority": "Chính phủ",
        "issued_date": "2025-11-10",
        "effective_date": "2026-01-01",
        "source_page_url": "https://vanban.chinhphu.vn/?classid=1&docid=215832&pageid=27160",
        "download_url": "https://datafiles.chinhphu.vn/cpp/files/vbpq/2025/11/293-cp.signed.pdf",
        "local_filename": "decree-293-2025-minimum-wage.pdf",
        "authoritative": True,
        "normative": True,
        "legal_status": "effective_from_2026_01_01",
        "active_corpus": True,
        "legal_topics": ["salary", "minimum_wage", "probation_salary"],
    },
    {
        "document_id": "decree_337_2025",
        "title": "Nghị định quy định về hợp đồng lao động điện tử",
        "document_number": "337/2025/NĐ-CP",
        "document_type": "decree",
        "issuing_authority": "Chính phủ",
        "issued_date": "2025-12-24",
        "effective_date": "2026-01-01",
        "source_page_url": "https://vanban.chinhphu.vn/?classid=0&docid=216284&pageid=27160",
        "download_url": "https://datafiles.chinhphu.vn/cpp/files/vbpq/2025/12/337-cp.signed.pdf",
        "local_filename": "decree-337-2025-electronic-labor-contract.pdf",
        "authoritative": True,
        "normative": True,
        "legal_status": "effective_from_2026_01_01",
        "active_corpus": True,
        "legal_topics": ["employment_contract", "electronic_contract"],
    },
    {
        "document_id": "circular_08_2026_bnv",
        "title": "Thông tư hướng dẫn Nghị định về hợp đồng lao động điện tử",
        "document_number": "08/2026/TT-BNV",
        "document_type": "circular",
        "issuing_authority": "Bộ Nội vụ",
        "issued_date": "2026-05-15",
        "effective_date": "2026-07-01",
        "source_page_url": "https://vanban.chinhphu.vn/?classid=0&docid=218200&pageid=27160",
        "download_url": "https://datafiles.chinhphu.vn/cpp/files/vbpq/2026/5/08-bnv.pdf",
        "local_filename": "circular-08-2026-electronic-labor-contract.pdf",
        "authoritative": True,
        "normative": True,
        "legal_status": "effective_from_2026_07_01",
        "active_corpus": True,
        "legal_topics": ["employment_contract", "electronic_contract"],
    },
)


GUIDANCE_SOURCES: Final[list[dict[str, Any]]] = [
    {
        "document_id": "guidance_worker_rights_overview",
        "url": "https://baochinhphu.vn/tu-2021-them-nhieu-quyen-loi-cho-nguoi-lao-dong-102285092.htm",
        "legal_topics": ["employment_contract", "annual_leave", "termination"],
    },
    {
        "document_id": "guidance_overtime_rules",
        "url": "https://baochinhphu.vn/lam-them-gio-the-nao-la-dung-quy-dinh-102240130085419703.htm",
        "legal_topics": ["overtime", "working_time"],
    },
    {
        "document_id": "guidance_overtime_salary",
        "url": "https://baochinhphu.vn/huong-dan-tinh-tien-luong-lam-them-gio-102250703162628452.htm",
        "legal_topics": ["overtime", "salary"],
    },
    {
        "document_id": "guidance_annual_leave_under_12_months",
        "url": "https://baochinhphu.vn/lam-viec-chua-du-12-thang-tinh-ngay-nghi-phep-the-nao-102260319095651248.htm",
        "legal_topics": ["annual_leave"],
    },
    {
        "document_id": "guidance_unilateral_termination",
        "url": "https://baochinhphu.vn/the-nao-la-don-phuong-cham-dut-hop-dong-lao-dong-dung-luat-102230428144412753.htm",
        "legal_topics": ["unilateral_termination", "contract_termination"],
    },
    {
        "document_id": "guidance_salary_delay",
        "url": "https://baochinhphu.vn/the-nao-la-cham-tra-luong-do-truong-hop-bat-kha-khang-102260303133428943.htm",
        "legal_topics": ["salary", "salary_delay", "unilateral_termination"],
    },
    {
        "document_id": "guidance_dismissal_conditions",
        "url": "https://baochinhphu.vn/dieu-kien-ap-dung-hinh-thuc-sa-thai-lao-dong-102251208144356042.htm",
        "legal_topics": ["dismissal", "labor_discipline"],
    },
    {
        "document_id": "guidance_probation_insurance",
        "url": "https://baochinhphu.vn/hop-dong-thu-viec-khong-dong-bhxh-bat-buoc-102260303141003744.htm",
        "legal_topics": ["probation", "employment_contract"],
    },
    {
        "document_id": "guidance_probation_two_month_insurance",
        "url": "https://baochinhphu.vn/hop-dong-thu-viec-2-thang-co-phai-dong-bhxh-bat-buoc-102260610162251986.htm",
        "legal_topics": ["probation", "employment_contract"],
    },
    {
        "document_id": "guidance_salary_basis_2026",
        "url": "https://baochinhphu.vn/cac-can-cu-tra-luong-cho-nguoi-lao-dong-102260303135159746.htm",
        "legal_topics": ["salary", "minimum_wage"],
    },
]
